spring:
  application:
    name: spring-boot-monog
logging:
  file: app.log

server:
  port: 8080

#spring.data.mongodb.uri: mongodb://idgst-mongo:27017/digest
#spring.data.mongodb.uri: mongodb://52.91.243.251:27017/digest
